-- Схема контента сайта «Гоголь барбершоп».
-- Применяется идемпотентно при старте app.py.

CREATE TABLE IF NOT EXISTS settings (
    key        text PRIMARY KEY,
    value      text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS photos (
    slot       text PRIMARY KEY,
    label      text NOT NULL DEFAULT '',
    url        text NOT NULL DEFAULT '',
    position   integer NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS services (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position integer NOT NULL DEFAULT 0,
    num      text NOT NULL DEFAULT '',
    title    text NOT NULL DEFAULT '',
    price    text NOT NULL DEFAULT '',
    descr    text NOT NULL DEFAULT '',
    tags     text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS price_groups (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position integer NOT NULL DEFAULT 0,
    title    text NOT NULL DEFAULT '',
    visible  boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS price_rows (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL REFERENCES price_groups (id) ON DELETE CASCADE,
    position integer NOT NULL DEFAULT 0,
    name     text NOT NULL DEFAULT '',
    price    text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS price_rows_group_idx ON price_rows (group_id, position);

CREATE TABLE IF NOT EXISTS brands (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position integer NOT NULL DEFAULT 0,
    name     text NOT NULL DEFAULT '',
    tagline  text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS brand_items (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id integer NOT NULL REFERENCES brands (id) ON DELETE CASCADE,
    position integer NOT NULL DEFAULT 0,
    name     text NOT NULL DEFAULT '',
    note     text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS brand_items_brand_idx ON brand_items (brand_id, position);

-- Загруженные через админку файлы; сами файлы лежат в media/.
CREATE TABLE IF NOT EXISTS media (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename      text NOT NULL UNIQUE,
    original_name text NOT NULL DEFAULT '',
    size_bytes    bigint NOT NULL DEFAULT 0,
    uploaded_at   timestamptz NOT NULL DEFAULT now()
);

-- История правок: каждое сохранение кладёт сюда полный снимок контента.
CREATE TABLE IF NOT EXISTS content_revisions (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    document   jsonb NOT NULL
);
